### ISSUE TITLE
Not letting me do ANYTHING

### ISSUE THREAD

**Issue by astralghost69** [GSRHackZ/EdgyBot_Edgenuity_Bot#130]
the bot will not let me do anything. it chooses one class and goes to the course map and will non-stop reloading that page. the only thing im able to do is turn on and off the bot. and on afk mode its not doing the assignments or quizes.

**Comment by GSRHackZ** [comment]
Yes, this has been fixed in the latest update. Uninstall tampermonkey and reinstall then login again.

**Comment by astralghost69** [comment]
![Screenshot 2023-03-30 002302](https://user-images.githubusercontent.com/129336147/228729177-c0ee985e-cc7a-4cf5-8ea2-155045257c55.png)

**Comment by astralghost69** [comment]
I am still getting this screen

**Comment by ITAC85v2** [comment]
> I am still getting this screen
> ![Screenshot 2023-03-30 002302](https://user-images.githubusercontent.com/129336147/228729177-c0ee985e-cc7a-4cf5-8ea2-155045257c55.png)

EdgyBot still doesn't support lessons named "assignment", as the message states.

**Comment by astralghost69** [comment]
but it was working perfectly on all of them

**Comment by GSRHackZ** [comment]
no, you had it set to EdgyAFK and it sipped those. This ahs been patched. it doesn't skip them anymore. It clearly states assignments are not supported.
